name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
          - head
          - jruby-head

    name: Ruby ${{ matrix.ruby }}
    env:
      JRUBY_OPTS: "--debug"
    steps:

    - name: prepare java environment for jruby
      if: matrix.ruby == 'jruby-head'
      run: |
        apt-get install -y openjdk-21-jdk
        java -version
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake
