name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.0'
          - '2.1'
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - head
          - jruby
          - jruby-head
        include:
          - ruby: head
            continue-on-error: true
          - ruby: jruby-head
            continue-on-error: true

    name: Ruby ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install --without development --retry=3 --jobs=3
      env:
        JRUBY_OPTS: --debug

    - name: Run tests
      run: bundle exec rake
      env:
        JRUBY_OPTS: --debug
      continue-on-error: ${{ matrix.continue-on-error == true }}
